### PR TITLE
Update SKTilemapObject.swift - invertedPosition

### PR DESCRIPTION
**Pull request by DanieleBarone**
Added invertedPosition - it flips the Y coordinate, useful when working with the Sprite Kit coordinate system (Y-Axis is  Bottom Up)

### CODE REVIEW

**Comment by TomLinthwaite** [comment]
Thanks I can see that being useful. :)

**Comment by DanieleBarone** [comment]
Thank you, Tom. I appreciate the feedback. Please feel free to reject the pull when it does not fit the scope of your project.

**Comment by TomLinthwaite** [comment]
No problem. I'll have a look at this when I get home because I'm thinking the position should probably just be the one you'd get in Sprite Kit. I think at the moment it just copies what ever tiles sent in. Not sure if that's of any use so I might just invert it and have that set as the default position. Seems a bit confusing to have 2 position vars

**Comment by TomLinthwaite** [comment]
Hi Daniele, I changed up what you did a bit in the latest build. 
object.position is now the inverted position as this makes more sense.
object.rawPosition is the position as taken from the tmx file in case any body really needs to use this.

Also added a helper function for getObjectAtCoord that accepts a CGPoint.

**Comment by DanieleBarone** [comment]
Awesome! Thank you, Tom!!!

**Pull request merged**
